spring:
  application:
    name: poc

  # H2 Database Configuration (for easy build, no need to start the DB server)
  # comment this datasource if running on Postgres
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: testdb
    password: test

  # Postgres Database Configuration
  # Prerequisite: start database server by executing docker compose in test/ directory
#  datasource:
#    url: jdbc:postgresql://localhost:5436/poc-db
#    username: admin
#    password: pass
#    driver-class-name: org.postgresql.Driver

  # Liquibase Configuration
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:19373
    listeners: PLAINTEXT://localhost:19373
    advertised:
      listeners: PLAINTEXT://localhost:19373
    consumer:
      group-id: bet_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    template:
      default-topic: bet_placement_topic
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs